## Short Study

The purpose of this short study is to look at what has happened to GME over the last 2 years. 

## Data
We are going to look at data from FINRA **RegSHO** available:  at http://regsho.finra.org/

There are 5 sources of data: 
* CNMS:
* FNQC:
* FNRA:
* FNSQ:
* FNYX: 

The filenames are arranged as such:

``` XXXXshvolYYYYMMDD.txt ```

XXXX is one of the 5 data sources as an example

```CNMSshvol20190102.txt```

We need to generate a list of dates to pull from regSHO sites:

In [3]:
import pandas as pd

# Generate dates to pull logs with
x = pd.date_range(start='20190101',end='20210801',freq='D').strftime('%Y%m%d')
x

Index(['20190101', '20190102', '20190103', '20190104', '20190105', '20190106',
       '20190107', '20190108', '20190109', '20190110',
       ...
       '20210723', '20210724', '20210725', '20210726', '20210727', '20210728',
       '20210729', '20210730', '20210731', '20210801'],
      dtype='object', length=944)

You can see above that we can generate any range we want. I am going to store the data in my local drive under `shortdata/`

As an example we will pull one day from regsho and write the data to a file 

In [11]:
base_url = 'http://regsho.finra.org/'

XXXX = 'CNMS'
date = '20190102' # Jan 01 is a holiday and there is no data
postfix = '.txt'
filename = XXXX+'shvol'+date+postfix

# Check to make sure we got it right
ref_filename = 'CNMSshvol20190102.txt'
print(filename==ref_filename)

# point at where you want to store the data. 
dir = 'shortdata/'




True


In [15]:
# Now we will download the file using the requests library
import requests

url = base_url + filename
print(url)
r = requests.get(url)
s = requests.get(url).content
f=open(dir+filename,'wb')
f.write(s)
f.close


http://regsho.finra.org/CNMSshvol20190102.txt


<function BufferedWriter.close>

In [18]:
# Now with a little error checking so we can skip weekends and holidays. 

date = '20190101' # Jan 01 is a holiday and there is no data
filename = XXXX+'shvol'+date+postfix
url = base_url + filename

r = requests.get(url)

if r.status_code == 404:
    print('404 Error')
else:
    s = requests.get(url).content
    f=open(dir+filename,'wb')
    f.write(s)
    f.close


404 Error


## pull.py 
This is the function I use to get data from regsho 

```
import pandas as pd
import requests

# Generate dates to pull logs with
x = pd.date_range(start='20190101',end='20210801',freq='D').strftime('%Y%m%d')


burl = 'http://regsho.finra.org/'
dir = 'shortdata/'
#prefix = 'CNMSshvol' # NMS
#prefix = 'FNQCshvol' # NMS
#prefix = 'FNRAshvol' # NMS
prefix = 'FNSQshvol' # NMS
#prefix = 'FNYXshvol' # NMS

postfix = '.txt'
for idx in range(len(x)):
    url =""
    pull = x[idx]
    filename = prefix+pull+postfix
    url =burl+filename
    print(burl)
    r = requests.get(url)

    if r.status_code == 404:
        print('404 Error')
    else:
        s = requests.get(url).content
        f=open(dir+filename,'wb')
        f.write(s)
        f.close
```